version: '3.9'
services:
  nginx:
    image: nginx
    container_name: 'balancemsql'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '4020:4020'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bdm1
      - bdm2
      - bdm3
    networks:
      - backend

  bdm1:
    image: mysql
    container_name: 'bdm1'
    environment:
      MYSQL_ROOT_PASSWORD: "senha"
      MYSQL_DATABASE: banco_de_dados
#      - MYSQL_USER=usuario
#      - MYSQL_PASSWORD=senha
      MYSQL_LOG_SLAVE_UPDATES: ON
#    volumes:
#      - ./bdm1:/var/lib/mysql
    networks:
      - backend

  bdm2:
    image: mysql
    container_name: 'bdm2'
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=banco_de_dados
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
      - MYSQL_LOG_SLAVE_UPDATES=ON
    volumes:
      - ./bdm2:/var/lib/mysql
    networks:
      - backend

  bdm3:
    image: mysql
    container_name: 'bdm3'
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=banco_de_dados
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
      - MYSQL_LOG_SLAVE_UPDATES=ON
    volumes:
      - ./bdm3:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
